#!/usr/bin/env python3
"""Write constraints.txt capping every dependency at its newest release that is
at least MIN_AGE_DAYS old.

A version published in the last few days has not been vetted by anyone; most
supply-chain compromises are caught and yanked within that window. pip-compile
consumes the file so the lock never picks up a release younger than that.

Run with network access, then re-run pip-compile:

    python scripts/refresh-constraints.py
    ./scripts/refresh-requirements.sh
"""

from __future__ import annotations

import json
import sys
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

MIN_AGE_DAYS = 7
ROOT = Path(__file__).resolve().parent.parent


def newest_vetted(package: str, cutoff: datetime) -> str | None:
    url = f"https://pypi.org/pypi/{package}/json"
    with urllib.request.urlopen(url, timeout=30) as fh:
        data = json.load(fh)

    best: tuple[tuple[int, ...], str] | None = None
    for version, files in data["releases"].items():
        if not files or any(f.get("yanked") for f in files):
            continue
        uploaded = min(
            datetime.fromisoformat(f["upload_time_iso_8601"].replace("Z", "+00:00"))
            for f in files
        )
        if uploaded > cutoff:
            continue
        try:
            key = tuple(int(part) for part in version.split("."))
        except ValueError:
            continue  # pre-release or local version: skip
        if best is None or key > best[0]:
            best = (key, version)
    return best[1] if best else None


def main() -> int:
    # The package set is whatever the current lock resolves to, so that
    # transitive dependencies are capped as well as direct ones.
    lock = (ROOT / "requirements.txt").read_text().splitlines()
    packages = sorted({
        line.split("==")[0].strip()
        for line in lock
        if "==" in line and not line.startswith(" ")
    } | {
        line.strip()
        for line in (ROOT / "requirements.in").read_text().splitlines()
        if line.strip() and not line.startswith("#")
    })

    cutoff = datetime.now(timezone.utc) - timedelta(days=MIN_AGE_DAYS)
    out = [
        "# Generated by scripts/refresh-constraints.py — do not edit by hand.",
        f"# Caps every dependency at its newest release older than "
        f"{MIN_AGE_DAYS} days.",
    ]
    for package in packages:
        version = newest_vetted(package, cutoff)
        if version:
            out.append(f"{package}<={version}")
            print(f"{package:<32} <= {version}")
        else:
            print(f"{package:<32} -- no vetted release found, left uncapped",
                  file=sys.stderr)

    (ROOT / "constraints.txt").write_text("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
